### ISSUE TITLE
Limitations on Live Migration

### ISSUE THREAD

**Issue by anyandrea** [acend/kubevirt-basics-training#53]
The Limitation mentioned in https://kubevirt-basics.training.acend.ch/docs/live-migration/live-migration-introduction/

"Additionally, pod network binding of the bridge interface is not allowed" isn't true anymore, it's actually possible with the annotation: `kubevirt.io/allow-pod-bridge-network-live-migration`
(although the upstream doc of kubevirt says the same)

**Comment by phil-pona** [comment]
Thanks for the input, we will check and update the lab accordingly

**Comment by phil-pona** [comment]
fixed
